version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_URL=postgres://postgres:postgres@db:5432/rssAggregator?sslmode=disable
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rssAggregator
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
